### ISSUE TITLE
Command line agruments

### ISSUE THREAD

**Issue by mikolmogorov** [katerinakazantseva/metaPhase#1]
All "frequently changed" input parameters should be command line arguments, rather than strings in `params.py`. For example, paths to input / output files, or other parameters (coverage cutoffs etc) that might be frequently changed. It is ok to keep "internal" parameters somewhere in the config files - those that users are not expected to touch.

**Comment by katerinakazantseva** [comment]
usage: metaPhase.phase.py [-h] -o OUTPUT -b BAM -g GFA -f FA [-s SNP]

optional arguments:
  -h, --help            show this help message and exit
  -s SNP, --snp SNP     vcf file

required named arguments:
  -o OUTPUT, --output OUTPUT
                        output dir
  -b BAM, --bam BAM     bam file
  -g GFA, --gfa GFA     gfa file
  -f FA, --fa FA        fa file
