### ISSUE TITLE
Output directory as a parameter.

### ISSUE THREAD

**Issue by mikolmogorov** [katerinakazantseva/metaPhase#2]
Currently if I run freshly cloned metaphase, I get:

```
Traceback (most recent call last):
  File "/Users/kolmogorovma/Work/projects/metaPhase/metaPhase.phase.py", line 8, in <module>
    from cluster import cluster
  File "/Users/kolmogorovma/Work/projects/metaPhase/cluster.py", line 112, in <module>
    stats = open('output/stats.txt', 'a')
FileNotFoundError: [Errno 2] No such file or directory: 'output/stats.txt'
```

Output directory should be command line parameter, and it should be created if not exist.

**Comment by katerinakazantseva** [comment]
usage: metaPhase.phase.py [-h] -o OUTPUT -b BAM -g GFA -f FA [-s SNP]

optional arguments:
  -h, --help            show this help message and exit
  -s SNP, --snp SNP     vcf file

required named arguments:
  -o OUTPUT, --output OUTPUT
                        output dir
  -b BAM, --bam BAM     bam file
  -g GFA, --gfa GFA     gfa file
  -f FA, --fa FA        fa file
