### ISSUE TITLE
Raise error if bam index is missing

### ISSUE THREAD

**Issue by mikolmogorov** [katerinakazantseva/metaPhase#3]
Fail early and output meaningful error message if bam index is missing. Currently the pipeline continues and produces more cryptic errors.

**Comment by katerinakazantseva** [comment]
done 
Traceback (most recent call last):
  File "/Users/ekaterina.kazantseva/metaPhase/metaPhase.phase.py", line 2, in <module>
    from params import *
  File "/Users/ekaterina.kazantseva/metaPhase/params.py", line 35, in <module>
    raise Exception("No index file found (%s) Please create index using \"samtools index\"." % bam_index)
Exception: No index file found (/Users/ekaterina.kazantseva/MT/5strain_hifi_sim/minigraph/minigraph.bam.bai) Please create index using "samtools index".
