### ISSUE TITLE
Improve manual

### ISSUE THREAD

**Issue by mikolmogorov** [katerinakazantseva/metaPhase#31]
Make sure that the current manual is up to date. See https://github.com/KolmogorovLab/hapdup for a template what to include. Docker package is optional, I would instead prefer an easy-to-follow conda installation. 

In addition, let's have a small test case uploaded somewhere (e.g. zenodo.org), so that anyone can easily reproduce the commands and try metaPhase on their machine. Example here: https://github.com/fenderglass/Flye/blob/flye/docs/USAGE.md#-examples

**Comment by mikolmogorov** [comment]
Also minimum software version should be specified, e.e. `samtools>=1.14`, `bcftools>=1.14`.

**Comment by mikolmogorov** [comment]
From todays discussion, there are two priorities here: 
* Make a small test example upload it to zenodo.org, and describe a set of commands to download and run it.
* Describe the installation via conda. Describe how to create a new environment from scratch that will be sufficient to run. You can do it either though a command line example (that a user would copy) or a conda environemnt file. Overall, this should also be a set of terminal commands that user can copy and execute (given that conda is installed)

**Comment by mikolmogorov** [comment]
+ another important moment: provide commands to transition from the initial `gfa` to `fasta` generating `bam` alignment.

**Comment by katerinakazantseva** [comment]
done
