### ISSUE TITLE
Clean up code + terminal output

### ISSUE THREAD

**Issue by mikolmogorov** [katerinakazantseva/metaPhase#41]
Remove commented out code, or code that is never used - unless these is a god reason to keep it.

Comment out the terminal/log output that is no longer necessary, but do keep the useful debug output (in case something goes wrong with other user's runs).

**Comment by microbemarsh** [comment]
Since this is undoubtedly going to get some popularity, the conda install in the read.me should be `make -C submodules/Flye` instead of `make -C submodules/flye` with the current naming conventions of the package.

**Comment by mikolmogorov** [comment]
@microbemarsh oups, thanks for pointing that out - fixed!

**Comment by katerinakazantseva** [comment]
@fenderglass done, I also changed console logging level to INFO (file logging still have DEBUG level), to avoid excessive information
