### ISSUE TITLE
make -C submodules/Flye error

### ISSUE THREAD

**Issue by Penny2023James** [katerinakazantseva/metaPhase#71]
Hi I faced an error when I tried to make submodules/Flye 

#########################################################
z5438778@k250:~/stRainy $ make -C submodules/Flye
make: Entering directory '/home/z5438778/stRainy/submodules/Flye'
make -C /home/z5438778/stRainy/submodules/Flye/lib/minimap2 -j 4
make[1]: Entering directory '/home/z5438778/stRainy/submodules/Flye/lib/minimap2'
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  bseq.c -o bseq.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  sketch.c -o sketch.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  sdust.c -o sdust.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  options.c -o options.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  index.c -o index.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  chain.c -o chain.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  align.c -o align.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  hit.c -o hit.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  map.c -o map.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  format.c -o format.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  pe.c -o pe.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  esterr.c -o esterr.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  splitidx.c -o splitidx.o
cc -c -g -Wall -O2 -Wc++-compat  -msse2 -DHAVE_KALLOC  ksw2_ll_sse.c -o ksw2_ll_sse.o
cc -c -g -Wall -O2 -Wc++-compat  -msse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH  ksw2_extz2_sse.c -o ksw2_extz2_sse41.o
cc -c -g -Wall -O2 -Wc++-compat  -msse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH  ksw2_extd2_sse.c -o ksw2_extd2_sse41.o
cc -c -g -Wall -O2 -Wc++-compat  -msse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH  ksw2_exts2_sse.c -o ksw2_exts2_sse41.o
cc -c -g -Wall -O2 -Wc++-compat  -msse2 -mno-sse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH -DKSW_SSE2_ONLY  ksw2_extz2_sse.c -o ksw2_extz2_sse2.o
cc -c -g -Wall -O2 -Wc++-compat  -msse2 -mno-sse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH -DKSW_SSE2_ONLY  ksw2_extd2_sse.c -o ksw2_extd2_sse2.o
cc -c -g -Wall -O2 -Wc++-compat  -msse2 -mno-sse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH -DKSW_SSE2_ONLY  ksw2_exts2_sse.c -o ksw2_exts2_sse2.o
cc -c -g -Wall -O2 -Wc++-compat  -msse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH  ksw2_dispatch.c -o ksw2_dispatch.o
ar -csru libminimap2.a kthread.o kalloc.o misc.o bseq.o sketch.o sdust.o options.o index.o chain.o align.o hit.o map.o format.o pe.o esterr.o splitidx.o ksw2_ll_sse.o ksw2_extz2_sse41.o ksw2_extd2_sse41.o ksw2_exts2_sse41.o ksw2_extz2_sse2.o ksw2_extd2_sse2.o ksw2_exts2_sse2.o ksw2_dispatch.o
cc -g -Wall -O2 -Wc++-compat  main.o -o minimap2 -L. -lminimap2 -lm -lz -lpthread
/bin/ld: main.o: unable to initialize decompress status for section .debug_info
/bin/ld: main.o: unable to initialize decompress status for section .debug_info
/bin/ld: main.o: unable to initialize decompress status for section .debug_info
/bin/ld: main.o: unable to initialize decompress status for section .debug_info
main.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:46: minimap2] Error 1
make[1]: Leaving directory '/home/z5438778/stRainy/submodules/Flye/lib/minimap2'
make: *** [Makefile:25: /home/z5438778/stRainy/submodules/Flye/bin/flye-minimap2] Error 2
make: Leaving directory '/home/z5438778/stRainy/submodules/Flye'
############################################################################
Does anyone know how to solve this? 
Any suggestions are welcome 
Thank you

**Comment by mikolmogorov** [comment]
Hello,

This error may be caused by inconsistencies in your developer libraries. Are you using conda environment for building? I'd suggest trying to disable it and build with only system libraries. If that doesn't help, please provide more info about your system, and also `gcc --version` / `cc --version`

**Comment by Penny2023James** [comment]
Hi, Thank you for the quick response, I tried building it in a conda environment and without but both of them shows error.
Below is the error that showed when I build without conda env 
############################################################################
z5438778@k143:~/stRainy $ make -C submodules/Flye
make: Entering directory '/home/z5438778/stRainy/submodules/Flye'
make -C /home/z5438778/stRainy/submodules/Flye/lib/minimap2 -j 4
make[1]: Entering directory '/home/z5438778/stRainy/submodules/Flye/lib/minimap2'
cc -g -Wall -O2 -Wc++-compat  main.o -o minimap2 -L. -lminimap2 -lm -lz -lpthread
/bin/ld: main.o: unable to initialize decompress status for section .debug_info
/bin/ld: main.o: unable to initialize decompress status for section .debug_info
/bin/ld: main.o: unable to initialize decompress status for section .debug_info
/bin/ld: main.o: unable to initialize decompress status for section .debug_info
main.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:46: minimap2] Error 1
make[1]: Leaving directory '/home/z5438778/stRainy/submodules/Flye/lib/minimap2'
make: *** [Makefile:25: /home/z5438778/stRainy/submodules/Flye/bin/flye-minimap2] Error 2
make: Leaving directory '/home/z5438778/stRainy/submodules/Flye'
############################################################################
I am now using Linux k143 4.18.0-477.15.1.el8_8.x86_64, with gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)/ cc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)

**Comment by mikolmogorov** [comment]
Strange, something must be inconsistent in your developer environment / packages. The building error is in fact in the minimap2, so we don't have much control over that. Are you able to build other biolinformatics tools from source on this system?

**Comment by mikolmogorov** [comment]
Closed due to inactivity, feel free to reopen if the issue remains!
