### ISSUE TITLE
Low coverage - output files missing

### ISSUE THREAD

**Issue by brambloemen** [katerinakazantseva/metaPhase#80]
Hello!

I was trying out strainy for phasing E coli MAGs from a metagenomic assembly (ONT R10 data).
Specifically, I generated an initial Flye assembly from all reads of a complex metagenomics sample. I then extracted all reads aligning to contigs classified as E. coli.

Next, I used the following commands to generate a new assembly and run strainy on it:
`flye --nano-hq {input.reads} --meta --no-alt-contigs --keep-haplotypes -i 0 --out-dir Ecoli/Flye`
`strainy.py Ecoli/ecolreads.fastq.gz -g Ecoli/Flye/assembly_graph.gfa -o out_strainy -m nano -t 10`

Strainy ran succesfully, but in the out_strainy directory, i see none of these output files:
-     alignment_phased.bam
-     strain_unitigs.gfa 
-     strain_contigs.gfa 
-     strain_variants.vcf A
-     reference_unitig_info_table.csv 
-     phased_unitig_info_table.csv 
-     multiplicity_stats.txt 

I do see these files/directories though:
adj_M  bam  clusters  flye_inputs  flye_outputs  graphs  log_phase  preprocessing_data  root.log  vcf

Do you know why I don't get the output files?

Thanks,

Bram

**Comment by katerinakazantseva** [comment]
Hello Bram!

Thank you for the report! Could you please share` log_phase` dir ?

**Comment by mikolmogorov** [comment]
Hi Bram,

It looks like you may re running an older version of strainy, based on theh output that you see.

I recommend either reinstalling the latest version from github into a fresh bioconda envinorment, or alternatively use the docker container.  Before running on a larger dataset, you can verify that the toy example produces the expected output (https://github.com/katerinakazantseva/strainy?tab=readme-ov-file#quick-usage). You can also try a larger dataset from the tutorial (https://github.com/katerinakazantseva/strainy?tab=readme-ov-file#strainy-tutorial).

**Comment by mikolmogorov** [comment]
P.S. if you are updating a github repository via pull, make sure to run `git submodule update --init` to update submodules. A failsafe method is to do a fresh clone into a new directory..

**Comment by brambloemen** [comment]
Hi @fenderglass @katerinakazantseva ,

My bad, it looks like I was indeed running an older version instead of the latest release. I will update and try rerunning the tool.
Thank you
